import { useCallback, useMemo, useState } from 'react';
import { api, type TransactionQuery } from '../api/client';
import { Button, Card, EmptyState, ErrorState, LoadingState } from '../components/ui';
import { useApiData } from './data';

const pageSize = 15;
function openCase(caseId: string) { window.history.pushState({}, '', `/cases?case_id=${caseId}`); window.dispatchEvent(new PopStateEvent('popstate')); }

export function Transactions() {
  const initialSearch = new URLSearchParams(window.location.search).get('search') ?? undefined;
  const [query, setQuery] = useState<TransactionQuery>({ page: 1, pageSize, sortBy: 'created_at', sortDir: 'desc', search: initialSearch });
  const load = useCallback((signal: AbortSignal) => api.searchTransactions(query, signal), [query]);
  const { data, error, retry } = useApiData(load);
  const pages = useMemo(() => Math.max(1, Math.ceil((data?.total ?? 0) / pageSize)), [data]);
  const investigate = async (transactionId: string) => { const created = await api.createCase(transactionId); await api.investigateCase(created.case_id); openCase(created.case_id); };
  return <><header className="page-heading"><p className="eyebrow">Synthetic demo data</p><h1>Transactions</h1><p>Search, filter, sort, and open suspicious transactions for human-reviewed investigation.</p>{initialSearch === 'TX-DEMO-001' && <div className="demo-callout">Hero demo loaded. Click Investigate on TX-DEMO-001 to continue the evaluator flow.</div>}</header><Card title="Transaction queue"><div className="toolbar"><input aria-label="Search transactions" placeholder="Search transaction, customer, merchant, status" value={query.search ?? ''} onChange={(event) => setQuery({ ...query, page: 1, search: event.target.value })} /><select aria-label="Status filter" value={query.status ?? ''} onChange={(event) => setQuery({ ...query, page: 1, status: event.target.value || undefined })}><option value="">All statuses</option><option value="captured">captured</option><option value="authorized">authorized</option><option value="settled">settled</option><option value="failed">failed</option></select><select aria-label="Sort by" value={query.sortBy} onChange={(event) => setQuery({ ...query, sortBy: event.target.value as TransactionQuery['sortBy'] })}><option value="created_at">Created</option><option value="amount">Amount</option><option value="status">Status</option><option value="currency">Currency</option></select><Button onClick={() => setQuery({ ...query, sortDir: query.sortDir === 'asc' ? 'desc' : 'asc' })}>Sort {query.sortDir === 'asc' ? '↑' : '↓'}</Button></div>{!data && !error && <LoadingState label="Loading transactions…" />}{error && <ErrorState message={error} onRetry={retry} />}{data && (data.items.length ? <><div className="table-scroll"><table><caption className="sr-only">Synthetic transaction records</caption><thead><tr><th>Transaction</th><th>Customer</th><th>Amount</th><th>Status</th><th>Created</th><th /></tr></thead><tbody>{data.items.map((item) => <tr key={item.transaction_id}><td>{item.transaction_id}</td><td>{item.customer_id}</td><td>{item.currency} {Number(item.amount).toLocaleString()}</td><td>{item.status}</td><td>{new Date(item.created_at).toLocaleString()}</td><td><Button onClick={() => void investigate(item.transaction_id)}>Investigate</Button></td></tr>)}</tbody></table></div><div className="pagination"><Button disabled={(query.page ?? 1) <= 1} onClick={() => setQuery({ ...query, page: (query.page ?? 1) - 1 })}>Previous</Button><span>Page {query.page ?? 1} of {pages} · {data.total} transactions</span><Button disabled={(query.page ?? 1) >= pages} onClick={() => setQuery({ ...query, page: (query.page ?? 1) + 1 })}>Next</Button></div></> : <EmptyState title="No transactions found" detail="Adjust filters or seed synthetic demo data through the backend." />)}</Card></>;
}
